cluster-configs:
  db:
    namespace: core
    name: db-service
    port: 5432
    targetPort: 5432

  root-ingress:
    name: root-ingress
    namespace: digit-studio
    cert-issuer: "letsencrypt-prod"
    appRoot: digit-studio
    serviceName: digit-studio
    servicePort: 80

  nginx-errors:
    enabled: false
    name: nginx-errors
    namespace: core
    serviceName: nginx-errors
    servicePort: 80

  configmaps:
    egov-config:
      namespace: [ core, digit-studio ]
      name: egov-config
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"  

    egov-service-host:    
      name: egov-service-host
      namespace: [ core, digit-studio ]

  secrets:
    db: 
      namespace: [ core, backbone ]
      name: db

    egov-notification-sms:
      namespace: core
      name: egov-notification-sms

    egov-filestore:
      namespace: core
      name: egov-filestore

    egov-location: 
      namespace: core
      name: egov-location

    egov-pg-service: 
      namespace: core
      name: egov-pg-service                 


    egov-enc-service: 
      namespace: core
      name: egov-enc-service       

    egov-notification-mail: 
      namespace: core
      name: egov-notification-mail


    git-sync: 
      namespace: core
      name: git-creds   

    kibana: 
      namespace: core
      name: kibana-creds                       

    kibana-infra: 
      namespace: core
      name: kibana-infra-creds     

    pgadmin: 
      namespace: backbone
      name: pgadmin
  
    minio:
      namespace: backbone
      name: minio

    alertmanager:
      namespace: monitoring
      name: alertmanager-main      

    jenkins:
      namespace: backbone
      name: jenkins

    postgres:
      namespace: backbone
      name: postgres

    elasticsearch-master-creds:
      namespace: [ backbone, core ]
      name: elasticsearch-master-credentials

    kafka-kraft:
      name: release-name-kafka-kraft-cluster-id
      namespace: backbone

