repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://hub.jupyter.org/helm-chart/


templates:
  default: &default
    namespace: backbone
    missingFileHandler: Warn
    values:
      - namespace: backbone
      - ../environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
      - ../environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml


releases:
- name: cert-manager
  chart: ./cert-manager
  installed: true
  version: v1.13.3
  disableValidation: true
  <<: *default

- name: minio
  installed: false
  chart: ./minio
  version: 13.3.1
  <<: *default

- name: redis
  installed: true
  chart: ./redis
  version: 7.2.4
  <<: *default

- name: elasticsearch
  chart: ./elasticsearch
  version: 8.11.3
  <<: *default

- name: elasticsearch-data
  chart: ./elasticsearch-data
  version: 8.11.3
  <<: *default

- name: kibana
  chart: ./kibana
  version: 8.11.3
  force: true
  <<: *default

- name: kafka-kraft
  installed: true
  chart: ./kafka-kraft
  version: 26.2.0
  <<: *default
  set:
    - name: kraft.clusterId
      value: MpHmWfWr0exqnJAvfv8W9R

- name: ingress-nginx
  chart: ./ingress-nginx
  installed: true
  version: 4.10.0
  <<: *default

- name: pgadmin
  chart: ./pgadmin
  installed: true
  <<: *default
