# Common Labels
labels:
  app: "egov-mdms-service"
  group: "core"


ingress:
  enabled: true
  zuul: true
  context: "egov-mdms-service(/|$)(.*)"
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /mdms-v2/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
