{{- with index .Values "cluster-configs" "secrets" "db" }}
{{- if index . "password" }}
{{- $secretName := .name }}
{{- $namespaces := .namespace }}
{{- if kindIs "slice" $namespaces }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "db" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "db" "password" | b64enc | quote }}
  flyway-username: {{ index $.Values "cluster-configs" "secrets" "db" "flywayUsername" | b64enc | quote }}
  flyway-password: {{ index $.Values "cluster-configs" "secrets" "db" "flywayPassword" | b64enc | quote }}
---
{{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespaces }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "db" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "db" "password" | b64enc | quote }}
  flyway-username: {{ index $.Values "cluster-configs" "secrets" "db" "flywayUsername" | b64enc | quote }}
  flyway-password: {{ index $.Values "cluster-configs" "secrets" "db" "flywayPassword" | b64enc | quote }}
---
{{- end }}
{{- end }}
{{- end }}

