{{- with index .Values "secrets" "pgadmin" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ .email | b64enc | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .password | b64enc | quote }}
{{- end }}