#checking helmfile

environments:
  env:
    values:
      - ./charts/environments/env-secrets.yaml
      - ./charts/environments/env.yaml

---

helmfiles:
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml
#  - path: ./charts/core-services/coreservices-helmfile.yaml
  # - path: ./charts/monitoring/monitoring-helmfile.yaml
