configmaps:
  egov-config:
    name: egov-config
    namespace: core
    data:
      db-host: "postgresql.backbone:5432"
      db-name: "postgres" ## Add db-name
      db-url: "jdbc:postgresql://postgresql.backbone:5432/postgres"
      db-otel-url: "jdbc:otel:postgresql://selco-prod-db.c1yks4g2c2zp.ap-south-1.rds.amazonaws.com/selcodevdb"
      domain: "digit-lts.digit.org" ## Add your Domain Name
      egov-bnd-freedownload-tenants: pg.testing
      egov-bnd-live-citizen-tenants: pg.testing
      egov-internal-microservice-user-uuid: 606192d1-4c90-42d9-878f-2294bc7ab9a9
      egov-services-fqdn-name: "https://digit-lts.digit.org/"
      egov-state-level-tenant-id: "pg"
      state-level-tenant-id: "pg"
      es-host: "elasticsearch-data.backbone"
      es-indexer-host: "https://elasticsearch-data.backbone:9200/"
      flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa,classpath:/db/migration/main"
      kafka-brokers: "kafka-kraft-controller-headless.backbone:9092"
      kafka-infra-brokers: kafka-v2-infra.kafka-cluster:9092
      logging-level-jdbc: "DEBUG"
      mobile-validation-workaround: "true"
      serializers-timezone-in-ist: "true"
      server-tomcat-max-connections: "500"
      server-tomcat-max-threads: "10"
      sms-enabled: "true"
      spring-datasource-tomcat-initialSize: "1"
      spring-datasource-tomcat-max-active: "2"
      spring-jpa-show-sql: "true"
      timezone: Asia/Kolkata
      tracer-errors-provideexceptionindetails: "true"
      egov-bnd-freedownload-tenants: "pg.testing"
      egov-bnd-live-citizen-tenants: "pg.testing"
  egov-service-host:
    name: egov-service-host
    namespace: core
    data:
      egov-enc-service: "http://egov-enc-service.core:8080/"
      egov-accesscontrol: "http://egov-accesscontrol.core:8080/"
      egov-user: "http://egov-user.core:8080/"
      egov-user-egov: "http://egov-user.core:8080/"
      egov-location: "http://egov-location.core:8080/"
      egov-filestore: "http://egov-filestore.core:8080/"
      egov-localization: "http://egov-localization.core:8080/"
      egov-idgen: "http://egov-idgen.core:8080/"
      egov-otp: "http://egov-otp.core:8080/"
      egov-mdms-service: "http://egov-mdms-service.core:8080/"
      egov-workflow: "http://egov-workflow.core:8080/"
      egov-workflow-v2: "http://egov-workflow-v2.core:8080/"
      egov-indexer: "http://egov-indexer.core:8080/"
      egov-hrms: "http://egov-hrms.core:8080/"
      es-client: "http://elasticsearch-data-v1.es-cluster:9200"
      location: "http://location:8080/"
      pdf-service: "http://pdf-service.core:8080/"
      user-otp: "http://user-otp.core:8080/"
      egov-apportion-service: "http://egov-apportion-service:8080/"
      minio-url: "http://minio.backbone:9000/"
      zuul: "http://zuul:8080/"
      egov-url-shortening: "http://eus:8080/"
      vendor: "http://vendor.sanitation:8080"
      project: "http://project.core:8080/"
      individual: "http://individual.core:8080/"
      product: "http://product.core:8080/"
      facility: "http://facility.core:8080/"
      inbox: "http://inbox.core:8080/"
      pgr-services: "http://pgr-services.core:8080/"
      egov-pdf: "http://egov-pdf.core:8080/"
      egov-user-event: "http://egov-user-event.core:8080/"
      mdms-v2: "http://mdms-v2.core:8080/"
      health-project: 'http://health-project.core:8080/'
      health-individual: 'http://health-individual.core:8080/'
      boundary-service: 'http://boundary-service.core:8080/'
      billing-service: 'http://billing-service.core:8080/'

root-ingress:
  name: root-ingress
  namespace: core
  cert-issuer: "letsencrypt-prod"
  appRoot: digit-studio
  serviceName: digit-studio
  servicePort: 80


secrets:
  db:
    name: db
    namespace: core
  git-sync:
    name: git-creds
    namespace: core
  pgadmin:
    name: pgadmin
    namespace: backbone
  egov-filestore:
    name: egov-filestore
    namespace: core
  egov-location:
    name: egov-location
    namespace: core
  egov-enc-service:
    name: egov-enc-service
    namespace: core
  egov-notification-sms:
    name: egov-notification-sms
    namespace: core
  egov-notification-mail:
    name: egov-notification-mail
    namespace: core
  elasticsearch:
    name: elasticsearch-master-credentials
    namespace: core
  alertmanager:
    name: alertmanager-main
    namespace: monitoring
  egov-hrms:
    name: egov-hrms
    namespace: core
  minio:
    name: minio
    namespace: core
