#checking helmfile
helmfiles:
  # - path: ./charts/cluster-configs/clusterconfigs-helmfile.yaml
  # - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  # - path: ./charts/core-services/coreservices-helmfile.yaml
  # - path: ./charts/monitoring/monitoring-helmfile.yaml
  - path: ./charts/studio-services/studioservices-helmfile.yaml
  # - path: ./charts/business-services/businessservices-helmfile.yaml   # for hrms service
  # - path: ./charts/health-services/healthservices-helmfile.yaml
