templates:
  default: &default
    version: 0.1.0
    namespace: egov
    missingFileHandler: Warn
    values:
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml

releases:
  - name: cluster-configs
    chart: .
    installed: true
    <<: *default
