templates:
  default: &default
    version: 0.1.0
    namespace: studio-dev
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - image:
          tag: '{{ requiredEnv "COMMON_TAG" }}'
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml


releases:
  - name: digit-studio # Replace with your desired namespace
    chart: ./digit-studio
    installed: true
    <<: *default

  - name: public-service # Replace with your desired namespace
    chart: ./public-service
    installed: true
    <<: *default

  - name: public-service-init # Replace with your desired namespace
    chart: ./public-service-init
    installed: true
    <<: *default

  - name: studio-individual # Replace with your desired namespace
    chart: ./studio-individual
    installed: true
    <<: *default

  - name: studio-pdf # Replace with your desired namespace
    chart: ./studio-pdf
    installed: true
    <<: *default

  - name: studio-service-request # Replace with your desired namespace
    chart: ./studio-service-request
    installed: true
    <<: *default

