global:
  image:
    tag: v2.9.2-4a60f20

boundary-service:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-accesscontrol:
  image:
    tag: master-1e8d2bb

egov-enc-service:
  image:
    tag: master-log-enc-ad23f2c
  initContainers:
    dbMigration:
      image:
        tag: master-log-enc-ad23f2c

egov-filestore:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-idgen:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-indexer:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-localization:
  image:
    tag: redis-localization-key-5c0a4c4
  initContainers:
    dbMigration:
      image:
        tag: redis-localization-key-5c0a4c4

egov-mdms-service:
  image:
    tag: v2.9.2-4a60f20

egov-notification-sms:
  image:
    tag: sandbox-d760d6b

egov-otp:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-persister:
  image:
    tag: master-3b238aa

egov-url-shortening:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

egov-user:
  image:
    tag: sandbox-log-f4a87d0
  initContainers:
    dbMigration:
      image:
        tag: sandbox-log-f4a87d0

egov-workflow-v2:
  image:
    tag: parallel-workflows-lazy-injection-1ace233
  initContainers:
    dbMigration:
      image:
        tag: parallel-workflows-lazy-injection-1ace233

inbox:
  image:
    tag: inbox-parallel-workflow-b5cd4a6

mdms-v2:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: master-1e8d2bb

pdf-service:
  image:
    tag: multiarch-master-99a308d
  initContainers:
    dbMigration:
      image:
        tag: master-aa460e8

user-otp:
  image:
    tag: sandbox-log-86902f9

egov-hrms:
  image:
    tag: hrms-boundary-individual-61e6097
  initContainers:
    dbMigration:
      image:
        tag: hrms-boundary-individual-61e6097

# === studio services === #

digit-studio:
  image:
    tag: studio-dev-ui-rc19-5-684a989-1415

public-service:
  image:
    tag: CCSD-1853-17eccfa
  initContainers:
    dbMigration:
      image:
        tag: CCSD-1853-17eccfa

public-service-init:
  image:
    tag: develop-9087218
  initContainers:
    dbMigration:
      image:
        tag: develop-9087218

studio-individual:
  image:
    tag: develop-586d99a
  initContainers:
    dbMigration:
      image:
        tag: develop-586d99a

studio-pdf:
  image:
    tag: develop-16d12f1

studio-service-request:
  image:
    tag: develop-586d99a
  initContainers:
    dbMigration:
      image:
        tag: develop-586d99a

health-individual:
  image:
    tag: master-nigeria-finalpull-dacaefe
  initContainers:
    dbMigration:
      image:
        tag: master-nigeria-finalpull-dacaefe

health-service-request:
  image:
    tag: multiarch-changes-digit-studio-3fd88be
  initContainers:
    dbMigration:
      image:
        tag: multiarch-changes-digit-studio-3fd88be