global:
  image:
    tag: v2.9.2-4a60f20


boundary-service:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-accesscontrol:
  image:
    tag: v2.9.2-4a60f20

egov-enc-service:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-filestore:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-idgen:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-indexer:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-localization:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-mdms-service:
  image:
    tag: v2.9.2-4a60f20

egov-notification-sms:
  image:
    tag: sandbox-d760d6b

egov-otp:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-persister:
  image:
    tag: v2.9.2-4a60f20

egov-url-shortening:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

egov-user:
  image:
    tag: sandbox-2.9.2-merge-857f015
  initContainers:
    dbMigration:
      image:
        tag: sandbox-2.9.2-merge-3ba6630

egov-workflow-v2:
  image:
    tag: v2.9.2-4a60f20
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

inbox:
  image:
    tag: inbox-parallel-workflow-b5cd4a6

mdms-v2:
  image:
    tag: master-1e8d2bb
  initContainers:
    dbMigration:
      image:
        tag: v2.9.2-4a60f20

pdf-service:
  image:
    tag: multiarch-master-99a308d
  initContainers:
    dbMigration:
      image:
        tag: master-aa460e8

user-otp:
  image:
    tag: sandbox-log-86902f9

egov-hrms:
  image:
    tag: sandbox-063a102
  initContainers:
    dbMigration:
      image:
        tag: sandbox-063a102



# === studio services === #

digit-studio:
  image:
    tag: studio-dev-ui-rc19-3-c3e3c69-1044

public-service:
  image:
    tag: develop-4351bc1
  initContainers:
    dbMigration:
      image:
        tag: develop-4351bc1

public-service-init:
  image:
    tag: develop-22ff7b0
  initContainers:
    dbMigration:
      image:
        tag: develop-22ff7b0

studio-individual:
  image:
    tag: develop-586d99a
  initContainers:
    dbMigration:
      image:
        tag: develop-586d99a

studio-pdf:
  image:
    tag: develop-cd9f31a

studio-service-request:
  image:
    tag: develop-586d99a
  initContainers:
    dbMigration:
      image:
        tag: develop-586d99a

health-individual:
  image:
    tag: master-fields-validation-changes-f6f8c3a
  initContainers:
    dbMigration:
      image:
        tag: master-fields-validation-changes-f6f8c3a

health-service-request:
  image:
    tag: master-eb25d83
  initContainers:
    dbMigration:
      image:
        tag: master-eb25d83
