repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://hub.jupyter.org/helm-chart/


templates:
  default: &default
    namespace: backbone-dev
    missingFileHandler: Warn
    values:
      - namespace: backbone-dev
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
      - ../../environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml


releases:
  - name: minio
    chart: ./minio
    version: 13.3.1
    installed: true
    <<: *default

  - name: postgres
    chart: ./postgres
    version: 11.9.13
    installed: true
    <<: *default

  - name: redis
    chart: ./redis
    version: 7.2.4
    installed: true
    <<: *default

  - name: elasticsearch
    chart: ./elasticsearch-master
    version: 8.11.3
    installed: true
    <<: *default

  - name: elasticsearch-data
    chart: ./elasticsearch-data
    version: 8.11.3
    installed: true
    <<: *default

  - name: kafka-kraft
    chart: ./kafka-kraft
    version: 26.2.0
    installed: true
    <<: *default

  - name: cert-manager
    chart: ./cert-manager
    version: v1.16.2
    installed: true
    disableValidation: true
    <<: *default

  - name: kibana
    chart: ./kibana
    version: 8.11.3
    installed: true
    force: true
    <<: *default

  - name: ingress-nginx
    chart: ./ingress-nginx
    version: 4.10.0
    installed: true
    <<: *default

  - name: playground
    chart: ./playground
    version: 0.1.0
    installed: true
    <<: *default

  - name: jupyterhub
    chart: ./jupyterhub
    version: 4.0.0
    installed: true
    disableValidation: true
    skipSchemaValidation: true
    <<: *default

  - name: pgadmin4
    chart: ./pgadmin
    version: 4.0.0
    installed: true
    <<: *default
