name: DIGIT-Install workflow for Testing


on:
  workflow_dispatch:
    inputs:
      create_infra:
        description: "Create/Update infracture before deploying."
        type: boolean
        required: true
        default: false


jobs:
  Infra_creation:
    if: ${{ github.event.inputs.create_infra }}
    uses: ./.github/workflows/infra_setup.yaml
    with:
      environment: env
    secrets: inherit

  DIGIT-deployment:
    needs: Infra_creation
    if: ${{ !cancelled() && !failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ vars.CLUSTER_NAME }}

      - name: Install sops
        run: |
          sudo apt update
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops

      - name: Decrypt secrets
        working-directory: ./deploy-as-code/helm
        run: sops -d -i --kms ${{ secrets.PUBLIC_KMS_KEY }} ./environments/testing-secrets.yaml

      - name: Install Helmfile
        uses: helmfile/helmfile-action@v2.2.0
        with:
          helm-version: 'v3.11.0'
          helmfile-version: "v0.150.0"
          helm-plugins: https://github.com/databus23/helm-diff@v3.1.3

      - name: Parse YAML and export as environment variables
        working-directory: ./deploy-as-code/product-releases
        run: |
          services=$(yq e '.modules[]
            | select(.name == "core" or .name == "digit-studio")
            | .services' ./v2.9.2.yaml)
          echo "$services" | sed "s/: /=/g" >> $GITHUB_ENV

      - name: Digit deployment
        working-directory: ./deploy-as-code/helm
        env:
          HELMFILE_ENV: "testing"
        run: |
          helmfile -f digit-helmfile.yaml template --include-needs=true\
            --set digit-studio.image.tag=${{ env.digit-studio }}\
            --set public-service.image.tag=${{ env.public-service }}\
            --set public-service-init.image.tag=${{ env.public-service-init }}\
            --set studio-individual.image.tag=${{ env.studio-individual }}\
            --set studio-pdf.image.tag=${{ env.studio-pdf }}\
            --set studio-service-request.image.tag=${{ env.studio-service-request }}\
            --set health-individual.image.tag=${{ env.health-individual }}\
            --set health-service-request.image.tag=${{ env.health-service-request }}\
            --set boundary-service.image.tag=${{ env.boundary-service }}\
            --set egov-accesscontrol.image.tag=${{ env.egov-accesscontrol }}\
            --set egov-enc-service.image.tag=${{ env.egov-enc-service }}\
            --set egov-filestore.image.tag=${{ env.egov-filestore }}\
            --set egov-idgen.image.tag=${{ env.egov-idgen }}\
            --set egov-indexer.image.tag=${{ env.egov-indexer }}\
            --set egov-localization.image.tag=${{ env.egov-localization }}\
            --set egov-mdms-service.image.tag=${{ env.egov-mdms-service }}\
            --set egov-notification-sms.image.tag=${{ env.egov-notification-sms }}\
            --set egov-otp.image.tag=${{ env.egov-otp }}\
            --set egov-persister.image.tag=${{ env.egov-persister }}\
            --set egov-url-shortening.image.tag=${{ env.egov-url-shortening }}\
            --set egov-user.image.tag=${{ env.egov-user }}\
            --set egov-workflow-v2.image.tag=${{ env.egov-workflow-v2 }}\
            --set inbox.image.tag=${{ env.inbox }}\
            --set mdms-v2.image.tag=${{ env.mdms-v2 }}\
            --set pdf-service.image.tag=${{ env.pdf-service }}\
            --set user-otp.image.tag=${{ env.user-otp }}\
            --set egov-hrms.image.tag=${{ env.egov-hrms }}
